Optimization Notebook

In [16]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [18]:
# Optimization 1 - removing columns
status_count1 = application_df['STATUS'].value_counts()[1]
consideration_count = application_df['SPECIAL_CONSIDERATIONS'].value_counts()['N']

print(f"The count of '1' in STATUS column is: {status_count1}")
print(f"The count of 'N' in SPECIAL_CONSIDERATIONS column is: {consideration_count}")

The count of '1' in STATUS column is: 34294
The count of 'N' in SPECIAL_CONSIDERATIONS column is: 34272

In [19]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
# Drop 'STATUS and 'SPECIAL_CONSIDERATIONS'
application_df = application_df.drop(["EIN","NAME","STATUS","SPECIAL_CONSIDERATIONS"], axis=1)
application_df.head(25)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
5,T3,Independent,C1200,Preservation,Trust,0,5000,1
6,T3,Independent,C1000,Preservation,Trust,100000-499999,31452,1
7,T3,Independent,C2000,Preservation,Trust,10M-50M,7508025,1
8,T7,Independent,C1000,ProductDev,Trust,1-9999,94389,1
9,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
10,T3,Independent,C1200,Preservation,Trust,25000-99999,69656,0
11,T3,Independent,C2000,Preservation,Trust,100000-499999,165593,0
12,T3,CompanySponsored,C1200,Preservation,Association,0,5000,1
13,T3,Independent,C2700,Preservation,Trust,25000-99999,5301,1
14,T3,Independent,C1000,Preservation,Trust,0,5000,1
15,T3,Independent,C1200,Preservation,Trust,0,5000,1
16,T3,Independent,C2000,Preservation,Trust,0,5000,1
17,T3,Independent,C1000,Heathcare,Trust,50M+,86380556,0
18,T3,CompanySponsored,C1000,Preservation,Trust,0,5000,0
19,T3,CompanySponsored,C1000,Preservation,Trust,100000-499999,376109,0
20,T4,Independent,C3000,ProductDev,Trust,0,5000,1
21,T3,Independent,C1200,Preservation,Trust,0,5000,1
22,T3,Independent,C7000,Preservation,Trust,100000-499999,318296,0
23,T4,CompanySponsored,C3000,ProductDev,Association,0,5000,0
24,T3,CompanySponsored,C1200,Preservation,Trust,0,5000,0

In [20]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [22]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9','T13','T12','T2','T25','T14','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [23]:
cls_tokeep = ['C1000','C2000','C1200','C3000','C2100']

def replace_cls(cls):
  if cls not in cls_tokeep:
    return 'other'
  else:
    return cls

# Apply to df
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].apply(replace_cls)

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [24]:
# Convert categorical data to numeric with `pd.get_dummies`
non_dummy_cols = ['ASK_AMT','IS_SUCCESSFUL']

dummy_cols = list(set(application_df.columns) - set(non_dummy_cols))
application_df = pd.get_dummies(application_df, columns=dummy_cols)
application_df.head()

,ASK_AMT,IS_SUCCESSFUL,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,...,AFFILIATION_Regional,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8
0,5000,1,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,108590,1,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2,5000,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,6692,1,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,142590,1,0,0,0,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0

In [25]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

<ipython-input-25-95d2e00f4d32>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = application_df.drop(["IS_SUCCESSFUL"],1).values

In [26]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [27]:
# Optimization 2 & 3: Adding more neurons to hidden layer 1&2 and adding an additional hidden layer
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  100
hidden_nodes_layer2 = 50
hidden_nodes_layer3 = 25

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               4100

 dense_1 (Dense)             (None, 50)                5050

 dense_2 (Dense)             (None, 25)                1275

 dense_3 (Dense)             (None, 1)                 26

=================================================================
Total params: 10451 (40.82 KB)
Trainable params: 10451 (40.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [29]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 2ms/step - loss: 0.5684 - accuracy: 0.7193
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5538 - accuracy: 0.7295
Epoch 3/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5512 - accuracy: 0.7329
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7321
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7329
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7328
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7328
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7332
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7342
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7350
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7344
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7342
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7352
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7361
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7357
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7365
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7366
Epoch 18/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5420 - accuracy: 0.7368
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5423 - accuracy: 0.7366
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7365
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5417 - accuracy: 0.7367
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5415 - accuracy: 0.7368
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7377
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7380
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7379
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7365
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7371
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5403 - accuracy: 0.7379
Epoch 29/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5394 - accuracy: 0.7382
Epoch 30/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5395 - accuracy: 0.7381
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5391 - accuracy: 0.7384
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7385
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5391 - accuracy: 0.7387
Epoch 34/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5391 - accuracy: 0.7387
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7376
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7378
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7386
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7386
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7395
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7390
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7399
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7387
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7392
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7385
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7385
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7392
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7392
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7396
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7388
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7398
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7389
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7391
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7399
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7393
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7407
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7390
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7397
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7398
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7398
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7394
Epoch 61/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7397
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7395
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7397
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7402
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7397
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7389
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7402
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7387
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7388
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7398
Epoch 71/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5344 - accuracy: 0.7407
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7397
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7398
Epoch 74/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7401
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7407
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7405
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7397
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7403
Epoch 81/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7403
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7404
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7406
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7402
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7403
Epoch 86/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7404
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7398
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7402
Epoch 89/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5337 - accuracy: 0.7404
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7409
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7407
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7410
Epoch 93/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7404
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7408
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7399
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7405
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5340 - accuracy: 0.7398
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7409
Epoch 99/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5327 - accuracy: 0.7408
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7408

In [30]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5627 - accuracy: 0.7287 - 549ms/epoch - 2ms/step
Loss: 0.5627292990684509, Accuracy: 0.7287463545799255

In [31]:
# Export our model to HDF5 file
save_format = 'h5'
nn.save('AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(